# This patch adds the args to allow exposing the metrics endpoint using HTTP
# Set 8443 to use HTTPS instead
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --metrics-bind-address=:8080

- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --metrics-secure=false

- op: add
  path: /spec/template/spec/containers/0/ports/-
  value:
    containerPort: 8080
    name: metrics
    protocol: TCP
